### ISSUE TITLE
Is it compatible with Google Authenticator? 

### ISSUE THREAD

**Issue by yesvivek** [RavuAlHemio/cpptotp#1]
I used this library to generate 6 digit token to validate against Google Authenticator, but the digits are not matching. Is it expected to work?

**Comment by RavuAlHemio** [comment]
I've just verified it against my Google Authenticator (using the `gauche` sample program) and it generated the correct codes. Is your system time set correctly? Have you input the correct key?

**Comment by yesvivek** [comment]
Hi @RavuAlHemio , sorry for the confusion, I had some base-32 encoding issues which I have resolved now (was encoding twice). Thanks for your time, appreciate it..
